#!/usr/bin/env ruby

require_relative '../lib/sami'

path = ARGV[0]
source = File.read(path)
lexer = Sami::Lexer.new(source)
parser = Sami::Parser.new(lexer.start_reading)
interpreter = Sami::Interpreter.new

interpreter.interpret(parser.parse)

exit(0)

